-- Home Bar: run this file once in Supabase Dashboard -> SQL Editor.
-- Afterwards create one user in Authentication -> Users:
-- email: homebar-admin@example.com
-- password: choose your own strong password

create table if not exists public.bases (
  id bigint generated by default as identity primary key,
  name text not null unique
);

create table if not exists public.ingredients (
  id bigint generated by default as identity primary key,
  name text not null unique,
  in_stock boolean not null default true
);

create table if not exists public.cocktails (
  id bigint generated by default as identity primary key,
  name text not null unique,
  photo text,
  sweetness integer not null check (sweetness between 0 and 5),
  acidity integer not null check (acidity between 0 and 5),
  strength integer not null check (strength between 0 and 5),
  base_id bigint not null references public.bases(id)
);

create table if not exists public.cocktail_ingredients (
  cocktail_id bigint not null references public.cocktails(id) on delete cascade,
  ingredient_id bigint not null references public.ingredients(id),
  primary key (cocktail_id, ingredient_id)
);

alter table public.bases enable row level security;
alter table public.ingredients enable row level security;
alter table public.cocktails enable row level security;
alter table public.cocktail_ingredients enable row level security;

drop policy if exists "public read bases" on public.bases;
create policy "public read bases" on public.bases for select to anon, authenticated using (true);
drop policy if exists "public read ingredients" on public.ingredients;
create policy "public read ingredients" on public.ingredients for select to anon, authenticated using (true);
drop policy if exists "public read cocktails" on public.cocktails;
create policy "public read cocktails" on public.cocktails for select to anon, authenticated using (true);
drop policy if exists "public read cocktail ingredients" on public.cocktail_ingredients;
create policy "public read cocktail ingredients" on public.cocktail_ingredients for select to anon, authenticated using (true);

drop policy if exists "admin write bases" on public.bases;
create policy "admin write bases" on public.bases for all to authenticated
  using ((select auth.jwt()->>'email')='homebar-admin@example.com')
  with check ((select auth.jwt()->>'email')='homebar-admin@example.com');
drop policy if exists "admin write ingredients" on public.ingredients;
create policy "admin write ingredients" on public.ingredients for all to authenticated
  using ((select auth.jwt()->>'email')='homebar-admin@example.com')
  with check ((select auth.jwt()->>'email')='homebar-admin@example.com');
drop policy if exists "admin write cocktails" on public.cocktails;
create policy "admin write cocktails" on public.cocktails for all to authenticated
  using ((select auth.jwt()->>'email')='homebar-admin@example.com')
  with check ((select auth.jwt()->>'email')='homebar-admin@example.com');
drop policy if exists "admin write cocktail ingredients" on public.cocktail_ingredients;
create policy "admin write cocktail ingredients" on public.cocktail_ingredients for all to authenticated
  using ((select auth.jwt()->>'email')='homebar-admin@example.com')
  with check ((select auth.jwt()->>'email')='homebar-admin@example.com');

insert into public.bases(name) values
  ('Джин'),('Водка'),('Ром'),('Текила'),('Виски'),('Ликер'),('Безалкогольная')
on conflict (name) do nothing;

insert into public.ingredients(name) values
  ('Джин'),('Красный вермут'),('Кампари'),('Апельсин'),('Лимонный сок'),('Сахарный сироп'),('Базилик'),
  ('Водка'),('Кофейный ликер'),('Эспрессо'),('Имбирное пиво'),('Лаймовый сок'),('Лайм'),('Белый ром'),
  ('Темный ром'),('Апельсиновый ликер'),('Миндальный сироп'),('Текила'),('Соль'),('Бурбон'),('Ангостура'),
  ('Сахар'),('Амаретто'),('Белок'),('Тоник'),('Огурец')
on conflict (name) do nothing;

insert into public.cocktails(name,sweetness,acidity,strength,base_id)
select v.name,v.sweetness,v.acidity,v.strength,b.id
from (values
  ('Негрони',2,1,4,'Джин'),('Бэзил Смэш',2,3,3,'Джин'),('Эспрессо Мартини',3,0,3,'Водка'),
  ('Московский мул',2,3,3,'Водка'),('Дайкири',2,4,3,'Ром'),('Май Тай',4,3,4,'Ром'),
  ('Маргарита',2,4,3,'Текила'),('Олд Фэшн',2,0,5,'Виски'),('Амаретто Сауэр',4,4,2,'Ликер'),
  ('Садовый тоник',1,2,0,'Безалкогольная')
) as v(name,sweetness,acidity,strength,base_name)
join public.bases b on b.name=v.base_name
on conflict (name) do update set sweetness=excluded.sweetness,acidity=excluded.acidity,strength=excluded.strength,base_id=excluded.base_id;

insert into public.cocktail_ingredients(cocktail_id,ingredient_id)
select c.id,i.id from (values
  ('Негрони','Джин'),('Негрони','Красный вермут'),('Негрони','Кампари'),('Негрони','Апельсин'),
  ('Бэзил Смэш','Джин'),('Бэзил Смэш','Лимонный сок'),('Бэзил Смэш','Сахарный сироп'),('Бэзил Смэш','Базилик'),
  ('Эспрессо Мартини','Водка'),('Эспрессо Мартини','Кофейный ликер'),('Эспрессо Мартини','Эспрессо'),('Эспрессо Мартини','Сахарный сироп'),
  ('Московский мул','Водка'),('Московский мул','Имбирное пиво'),('Московский мул','Лаймовый сок'),('Московский мул','Лайм'),
  ('Дайкири','Белый ром'),('Дайкири','Лаймовый сок'),('Дайкири','Сахарный сироп'),
  ('Май Тай','Темный ром'),('Май Тай','Белый ром'),('Май Тай','Апельсиновый ликер'),('Май Тай','Миндальный сироп'),('Май Тай','Лаймовый сок'),
  ('Маргарита','Текила'),('Маргарита','Апельсиновый ликер'),('Маргарита','Лаймовый сок'),('Маргарита','Соль'),
  ('Олд Фэшн','Бурбон'),('Олд Фэшн','Ангостура'),('Олд Фэшн','Сахар'),('Олд Фэшн','Апельсин'),
  ('Амаретто Сауэр','Амаретто'),('Амаретто Сауэр','Лимонный сок'),('Амаретто Сауэр','Сахарный сироп'),('Амаретто Сауэр','Белок'),
  ('Садовый тоник','Тоник'),('Садовый тоник','Огурец'),('Садовый тоник','Базилик'),('Садовый тоник','Лайм')
) as v(cocktail_name,ingredient_name)
join public.cocktails c on c.name=v.cocktail_name
join public.ingredients i on i.name=v.ingredient_name
on conflict do nothing;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values ('cocktail-photos','cocktail-photos',true,5242880,array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public=true,file_size_limit=5242880,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "public read cocktail photos" on storage.objects;
create policy "public read cocktail photos" on storage.objects for select to public using (bucket_id='cocktail-photos');
drop policy if exists "admin upload cocktail photos" on storage.objects;
create policy "admin upload cocktail photos" on storage.objects for insert to authenticated
  with check (bucket_id='cocktail-photos' and (select auth.jwt()->>'email')='homebar-admin@example.com');
drop policy if exists "admin update cocktail photos" on storage.objects;
create policy "admin update cocktail photos" on storage.objects for update to authenticated
  using (bucket_id='cocktail-photos' and (select auth.jwt()->>'email')='homebar-admin@example.com')
  with check (bucket_id='cocktail-photos' and (select auth.jwt()->>'email')='homebar-admin@example.com');
drop policy if exists "admin delete cocktail photos" on storage.objects;
create policy "admin delete cocktail photos" on storage.objects for delete to authenticated
  using (bucket_id='cocktail-photos' and (select auth.jwt()->>'email')='homebar-admin@example.com');
