-- Home Bar: run this file once in Supabase Dashboard -> SQL Editor.
-- Afterwards create one user in Authentication -> Users:
-- email: homebar-admin@example.com
-- password: choose your own strong password

create table if not exists public.bases (
  id bigint generated by default as identity primary key,
  name text not null unique
);

create table if not exists public.ingredients (
  id bigint generated by default as identity primary key,
  name text not null unique,
  in_stock boolean not null default true
);

create table if not exists public.cocktails (
  id bigint generated by default as identity primary key,
  name text not null unique,
  photo text,
  sweetness integer not null check (sweetness between 0 and 5),
  acidity integer not null check (acidity between 0 and 5),
  strength integer not null check (strength between 0 and 5),
  base_id bigint not null references public.bases(id)
);

create table if not exists public.cocktail_ingredients (
  cocktail_id bigint not null references public.cocktails(id) on delete cascade,
  ingredient_id bigint not null references public.ingredients(id),
  primary key (cocktail_id, ingredient_id)
);

create table if not exists public.cocktail_recipes (
  cocktail_id bigint primary key references public.cocktails(id) on delete cascade,
  proportions text[] not null default '{}',
  method text,
  glass text,
  garnish text,
  note text
);

alter table public.bases enable row level security;
alter table public.ingredients enable row level security;
alter table public.cocktails enable row level security;
alter table public.cocktail_ingredients enable row level security;
alter table public.cocktail_recipes enable row level security;

drop policy if exists "public read bases" on public.bases;
create policy "public read bases" on public.bases for select to anon, authenticated using (true);
drop policy if exists "public read ingredients" on public.ingredients;
create policy "public read ingredients" on public.ingredients for select to anon, authenticated using (true);
drop policy if exists "public read cocktails" on public.cocktails;
create policy "public read cocktails" on public.cocktails for select to anon, authenticated using (true);
drop policy if exists "public read cocktail ingredients" on public.cocktail_ingredients;
create policy "public read cocktail ingredients" on public.cocktail_ingredients for select to anon, authenticated using (true);
drop policy if exists "public read cocktail recipes" on public.cocktail_recipes;
create policy "public read cocktail recipes" on public.cocktail_recipes for select to anon, authenticated using (true);

drop policy if exists "admin write bases" on public.bases;
create policy "admin write bases" on public.bases for all to authenticated
  using ((select auth.jwt()->>'email')='homebar-admin@example.com')
  with check ((select auth.jwt()->>'email')='homebar-admin@example.com');
drop policy if exists "admin write ingredients" on public.ingredients;
create policy "admin write ingredients" on public.ingredients for all to authenticated
  using ((select auth.jwt()->>'email')='homebar-admin@example.com')
  with check ((select auth.jwt()->>'email')='homebar-admin@example.com');
drop policy if exists "admin write cocktails" on public.cocktails;
create policy "admin write cocktails" on public.cocktails for all to authenticated
  using ((select auth.jwt()->>'email')='homebar-admin@example.com')
  with check ((select auth.jwt()->>'email')='homebar-admin@example.com');
drop policy if exists "admin write cocktail ingredients" on public.cocktail_ingredients;
create policy "admin write cocktail ingredients" on public.cocktail_ingredients for all to authenticated
  using ((select auth.jwt()->>'email')='homebar-admin@example.com')
  with check ((select auth.jwt()->>'email')='homebar-admin@example.com');
drop policy if exists "admin write cocktail recipes" on public.cocktail_recipes;
create policy "admin write cocktail recipes" on public.cocktail_recipes for all to authenticated
  using ((select auth.jwt()->>'email')='homebar-admin@example.com')
  with check ((select auth.jwt()->>'email')='homebar-admin@example.com');

insert into public.bases(name) values
  ('Джин'),('Водка'),('Ром'),('Текила'),('Виски'),('Ликер'),('Безалкогольная'),('Игристое вино')
on conflict (name) do nothing;

insert into public.ingredients(name) values
  ('Джин'),('Красный вермут'),('Кампари'),('Апельсин'),('Лимонный сок'),('Сахарный сироп'),('Базилик'),
  ('Водка'),('Кофейный ликер'),('Эспрессо'),('Имбирное пиво'),('Лаймовый сок'),('Лайм'),('Белый ром'),
  ('Темный ром'),('Апельсиновый ликер'),('Миндальный сироп'),('Текила'),('Соль'),('Бурбон'),('Ангостура'),
  ('Сахар'),('Амаретто'),('Белок'),('Тоник'),('Огурец'),('Игристое вино'),('Апероль'),('Газированная вода')
on conflict (name) do nothing;

insert into public.cocktails(name,sweetness,acidity,strength,base_id)
select v.name,v.sweetness,v.acidity,v.strength,b.id
from (values
  ('Негрони',2,1,4,'Джин'),('Бэзил Смэш',2,3,3,'Джин'),('Эспрессо Мартини',3,0,3,'Водка'),
  ('Московский мул',2,3,3,'Водка'),('Дайкири',2,4,3,'Ром'),('Май Тай',4,3,4,'Ром'),
  ('Маргарита',2,4,3,'Текила'),('Олд Фэшн',2,0,5,'Виски'),('Амаретто Сауэр',4,4,2,'Ликер'),
  ('Садовый тоник',1,2,0,'Безалкогольная'),('Апероль Шпритц',3,2,2,'Игристое вино')
) as v(name,sweetness,acidity,strength,base_name)
join public.bases b on b.name=v.base_name
on conflict (name) do update set sweetness=excluded.sweetness,acidity=excluded.acidity,strength=excluded.strength,base_id=excluded.base_id;

insert into public.cocktail_ingredients(cocktail_id,ingredient_id)
select c.id,i.id from (values
  ('Негрони','Джин'),('Негрони','Красный вермут'),('Негрони','Кампари'),('Негрони','Апельсин'),
  ('Бэзил Смэш','Джин'),('Бэзил Смэш','Лимонный сок'),('Бэзил Смэш','Сахарный сироп'),('Бэзил Смэш','Базилик'),
  ('Эспрессо Мартини','Водка'),('Эспрессо Мартини','Кофейный ликер'),('Эспрессо Мартини','Эспрессо'),('Эспрессо Мартини','Сахарный сироп'),
  ('Московский мул','Водка'),('Московский мул','Имбирное пиво'),('Московский мул','Лаймовый сок'),('Московский мул','Лайм'),
  ('Дайкири','Белый ром'),('Дайкири','Лаймовый сок'),('Дайкири','Сахарный сироп'),
  ('Май Тай','Темный ром'),('Май Тай','Белый ром'),('Май Тай','Апельсиновый ликер'),('Май Тай','Миндальный сироп'),('Май Тай','Лаймовый сок'),
  ('Маргарита','Текила'),('Маргарита','Апельсиновый ликер'),('Маргарита','Лаймовый сок'),('Маргарита','Соль'),
  ('Олд Фэшн','Бурбон'),('Олд Фэшн','Ангостура'),('Олд Фэшн','Сахар'),('Олд Фэшн','Апельсин'),
  ('Амаретто Сауэр','Амаретто'),('Амаретто Сауэр','Лимонный сок'),('Амаретто Сауэр','Сахарный сироп'),('Амаретто Сауэр','Белок'),
  ('Садовый тоник','Тоник'),('Садовый тоник','Огурец'),('Садовый тоник','Базилик'),('Садовый тоник','Лайм'),
  ('Апероль Шпритц','Игристое вино'),('Апероль Шпритц','Апероль'),('Апероль Шпритц','Газированная вода'),('Апероль Шпритц','Апельсин')
) as v(cocktail_name,ingredient_name)
join public.cocktails c on c.name=v.cocktail_name
join public.ingredients i on i.name=v.ingredient_name
on conflict do nothing;

insert into public.cocktail_recipes(cocktail_id,proportions,method,glass,garnish,note)
select c.id,v.proportions,v.method,v.glass,v.garnish,v.note
from (values
  ('Негрони',array['Джин — 30 мл','Кампари — 30 мл','Красный вермут — 30 мл'],'Смешайте ингредиенты со льдом в стакане для смешивания, перелейте в рокс и украсьте цедрой.','Рокс со льдом','Апельсиновая цедра',''),
  ('Бэзил Смэш',array['Джин — 50 мл','Лимонный сок — 25 мл','Сахарный сироп — 20 мл','Базилик — 8–10 листьев'],'Аккуратно разомните базилик с сиропом, добавьте джин, лимон и лёд. Встряхните и процедите.','Рокс или купе','Верхушка базилика',''),
  ('Эспрессо Мартини',array['Водка — 50 мл','Кофейный ликер — 25 мл','Эспрессо — 30 мл','Сахарный сироп — 10 мл'],'Хорошо встряхните всё со льдом до плотной пенки и процедите в охлаждённый бокал.','Охлаждённая коктейльная рюмка','3 кофейных зерна',''),
  ('Московский мул',array['Водка — 50 мл','Лаймовый сок — 15 мл','Имбирное пиво — 120 мл'],'Соберите напиток прямо в бокале со льдом, аккуратно перемешайте и украсьте лаймом.','Медная кружка или хайбол','Долька лайма',''),
  ('Дайкири',array['Белый ром — 50 мл','Лаймовый сок — 25 мл','Сахарный сироп — 20 мл'],'Встряхните ингредиенты со льдом и процедите в охлаждённый бокал.','Купе','Колесо лайма',''),
  ('Май Тай',array['Белый ром — 30 мл','Темный ром — 30 мл','Апельсиновый ликер — 15 мл','Миндальный сироп — 15 мл','Лаймовый сок — 25 мл'],'Встряхните всё со льдом, перелейте в рокс и досыпьте дроблёный лёд.','Рокс с дроблёным льдом','Мята и лайм',''),
  ('Маргарита',array['Текила — 50 мл','Апельсиновый ликер — 25 мл','Лаймовый сок — 25 мл'],'Встряхните со льдом и процедите в бокал. По желанию сделайте соляную кромку.','Купе или рокс с соляной кромкой','Долька лайма',''),
  ('Олд Фэшн',array['Бурбон — 60 мл','Сахар — 1 кубик или 10 мл сиропа','Ангостура — 2–3 дэша'],'Растворите сахар с биттером, добавьте лёд и бурбон, медленно перемешайте прямо в бокале.','Рокс','Апельсиновая цедра',''),
  ('Амаретто Сауэр',array['Амаретто — 50 мл','Лимонный сок — 25 мл','Сахарный сироп — 10 мл','Белок — 15 мл'],'Сначала встряхните без льда, затем со льдом. Процедите в рокс со свежим льдом.','Рокс','Лимон и коктейльная вишня',''),
  ('Садовый тоник',array['Тоник — 150 мл','Лайм — 2 дольки','Огурец — 3–4 слайса','Базилик — несколько листьев'],'Соберите в бокале со льдом, слегка прижмите лайм и базилик, долейте тоник.','Хайбол','Огурец и базилик',''),
  ('Апероль Шпритц',array['Игристое вино — 90 мл','Апероль — 60 мл','Газированная вода — 30 мл'],'Наполните бокал льдом, влейте игристое, Апероль и воду. Легко перемешайте.','Большой винный бокал','Долька апельсина','')
) as v(cocktail_name,proportions,method,glass,garnish,note)
join public.cocktails c on c.name=v.cocktail_name
on conflict (cocktail_id) do nothing;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values ('cocktail-photos','cocktail-photos',true,5242880,array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public=true,file_size_limit=5242880,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "public read cocktail photos" on storage.objects;
create policy "public read cocktail photos" on storage.objects for select to public using (bucket_id='cocktail-photos');
drop policy if exists "admin upload cocktail photos" on storage.objects;
create policy "admin upload cocktail photos" on storage.objects for insert to authenticated
  with check (bucket_id='cocktail-photos' and (select auth.jwt()->>'email')='homebar-admin@example.com');
drop policy if exists "admin update cocktail photos" on storage.objects;
create policy "admin update cocktail photos" on storage.objects for update to authenticated
  using (bucket_id='cocktail-photos' and (select auth.jwt()->>'email')='homebar-admin@example.com')
  with check (bucket_id='cocktail-photos' and (select auth.jwt()->>'email')='homebar-admin@example.com');
drop policy if exists "admin delete cocktail photos" on storage.objects;
create policy "admin delete cocktail photos" on storage.objects for delete to authenticated
  using (bucket_id='cocktail-photos' and (select auth.jwt()->>'email')='homebar-admin@example.com');
